📝Documentation as static website
AckeeCZ/ACKategories pull request #144
Opened 2024-01-28 15:18 UTC by nadvitek

Added GitHub Action to build ACKategories documentation and deploy it as a static website with Github Pages.

2024-01-28 18:21 UTC, olejnjak requested changes

2024-01-28 18:21 UTC, olejnjak commented on .github/workflows/docbuild.yml
> +    runs-on: macos-12
I would prefer running on macOS 13 as all other jobs do.

2024-01-28 18:21 UTC, olejnjak commented on .github/workflows/docbuild.yml
> +          xcodebuild docbuild -scheme ACKategories \
As long as you use xcodebuild I would call the load xcode version action as all other actions do to make sure you use correct Xcode version

2024-01-28 18:21 UTC, olejnjak commented on .github/workflows/docbuild.yml
> +        uses: actions/checkout@v3
Would be good to use latest checkout version - v4

2024-01-29 10:51 UTC, olejnjak approved these changes

2024-01-30 10:45 UTC, IgorRosocha approved these changes
LGTM, good job. 🙌

2024-01-30 12:17 UTC, merged