💄 Add fit to readable content layout guide
AckeeCZ/ACKategories pull request #151
Opened 2024-12-06 10:51 UTC by komkovla

# Add SwiftUI Layout Guides

## Description
Adds utilities for working with SwiftUI layout margins and readable content guides. This implementation is based on the work from [swiftui-layout-guides](https://github.com/tgrapperon/swiftui-layout-guides) and provides a clean API for handling layout constraints in SwiftUI.

### Key Features:
- `WithLayoutMargins` view for accessing layout margins and readable content insets
- View modifiers for fitting content to readable width or layout margins width:
  - `.fitToReadableContentWidth()`
  - `.fitToLayoutMarginsWidth()`
- Environment values for accessing layout metrics:
  - `layoutMarginsInsets`
  - `readableContentInsets`

## Usage Example
```swift
struct ContentView: View {
  var body: some View {
    Text("Hello World")
    .frame(maxWidth: .infinity)
    .fitToReadableContentWidth() // Constrains text to readable width
  }
}
```

## Platform Support
- iOS
- tvOS
- macOS (partial support)
- watchOS (partial support)

## Testing
Includes preview examples demonstrating usage in:
- ScrollView
- List with different styles
- Split view layouts

## Attribution
Original implementation inspired by [@tgrapperon](https://github.com/tgrapperon)'s swiftui-layout-guides library.

2024-12-06 15:28 UTC, olejnjak requested changes

2024-12-06 15:28 UTC, olejnjak commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +public struct FitReadableContentWidth<Content>: View where Content: View {
I would rather not add a code that is already marked as deprecated, can we remove it?

2024-12-06 15:28 UTC, olejnjak commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +public struct FitLayoutMarginsWidth<Content>: View where Content: View {
Same here.

2024-12-06 15:28 UTC, olejnjak commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +struct LayoutGuidesModifier: ViewModifier {
I would rather keep top level objects explicitly state that they are internal

2025-01-17 01:57 UTC, olejnjak commented
@komkovla

2025-01-21 09:41 UTC, komkovla commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +public struct FitReadableContentWidth<Content>: View where Content: View {
Fixed in [8fb85bf](https://github.com/AckeeCZ/ACKategories/pull/151/commits/8fb85bf22a2f4ab65b15d2583040a424ca9d830e)

2025-01-21 10:03 UTC, komkovla commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +@available(iOS 13.0, *)
You are right, I will check other platforms and add missing conditions

2025-01-21 10:04 UTC, olejnjak commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +@available(iOS 13.0, *)
I would say you are looking for this https://github.com/AckeeCZ/ACKategories/blob/main/Sources/ACKategories/SwiftUIExtensions/View%2BFrame.swift#L3

2025-01-21 10:04 UTC, komkovla commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +struct LayoutGuidesModifier: ViewModifier {
Added in [f83babb](https://github.com/AckeeCZ/ACKategories/pull/151/commits/f83babb7637c94f57eef51541a41ec30348c0db0)

2025-01-21 10:52 UTC, komkovla commented on Sources/ACKategories/SwiftUIExtensions/SwiftUILayoutGuides.swift
> +@available(iOS 13.0, *)
Fixed in [09b39de](https://github.com/AckeeCZ/ACKategories/pull/151/commits/09b39de3a635839dd86d78ca74c0b5db46dd669f)

2025-01-21 12:17 UTC, olejnjak approved these changes
LGTM!

2025-01-21 12:18 UTC, merged